### ISSUE TITLE
Please publish it on the standard repo

### ISSUE THREAD

**Issue by pcav** [geosim/QAD#3]
For better availability and wider testing.
http://plugins.qgis.org/

**Comment by geosim** [comment]
We are waiting for lawyer counsel.

**Comment by pcav** [comment]
IMHO from a legal point of view there is no difference between publishing on github and on http://plugins.qgis.org

**Comment by lbartoletti** [comment]
I also think it would be good to publish it in the official repertory. 

If you do it, it will also merge our projects (https://github.com/lbartoletti/CADDigitize).
Your base is perfect, it will only remain to add functions on ellipses for example.

regards

Actually QAD doesn't support ellipse. Till now, ellipse support is not be considered as a priority. This can be a new feature but it will take long time to develope due to: "identification" of an existing ellipse, all intersection calculations between ellipses and other type of QAD geometry (line, arcs, circles...), command ELLIPSE.
Thanks for suggestion
